### ISSUE TITLE
文件名的校验问题

### ISSUE THREAD

**Issue by BigKongfuPanda** [holyzfy/validate_filename#1]
只允许使用小写的文件名，但是将文件名中大写的字母改成了小写后，commit的时候依然提示出错，依然是大写的。  

> 约定文件名由小写字母、数字、_组成

**Comment by holyzfy** [comment]
Mac系统对大小写不敏感，可能需要执行`git mv`命令试试，例如`git mv Folder folder`

**Comment by BigKongfuPanda** [comment]
@holyzfy 哦，下次试试。我后来把文件剪切后暂存起来，然后运行一遍 git commit ，再把 文件从暂存区copy回来，再运行 commit 就好了。
